### ISSUE TITLE
Mavproxy :-Exception in thread main loop , An existing connection was forcibly closed by remote host on windows

### ISSUE THREAD

**Issue by sakshamgupta006** [diydrones/ardupilot-wiki-issue-tracker#242]
I am getting the following error in Mavproxy after  type in the command sim_vehicle.sh -j4 --map in Arduplane directory

Connect tcp:127.0.0.1:5760 source_system=255
Loaded module map
Running script C:\Users\Saksham\AppData\Local\MAVProxy\mavinit.scr
-> set moddebug 2
-> module load graph
Loaded module graph
-> module load console
Loaded module console
Loaded module help
Log Directory:
Telemetry log: mav.tlog
MAV> Waiting for heartbeat from tcp:127.0.0.1:5760
MAV> Exception in thread main_loop:
Traceback (most recent call last):
  File "C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.pyz\threading", line 810, in __bootstrap_inner
  File "C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.pyz\threading", line 763, in run
  File "<string>", line 717, in main_loop
  File "C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.pyz\pymavlink.mavutil", line 374, in wait_heartbeat
  File "C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.pyz\pymavlink.mavutil", line 339, in recv_match
  File "C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.pyz\pymavlink.mavutil", line 302, in recv_msg
  File "C:\Users\Stephen\Documents\MAVProxy\MAVProxy\build\mavproxy\out00-PYZ.pyz\pymavlink.mavutil", line 885, in recv
error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by hamishwillee** [comment]
Hi @sakshamgupta006 

Please re-post this in the MAVProxy repo [here](https://github.com/Dronecode/MAVProxy/issues) - please include the platform you're running MAVProxy on and the version of MAVProxy.

Regards
Hamish
